#!/bin/sh
#


: << =cut

=head1 NAME

wmr_wind - Plugin to monitor WMR weather wind sensors WGR800 or other...
wmr_wind

=head1 CONFIGURATION

The following enviroment variables are used by this plugin:

 wmrconf - full path to config file to use. (Default /etc/wmr/wmr.conf)

=head1 USAGE

Place the plugin in the /etc/munin/plugins/ directory, and make it
executable.

=head1 AUTHOR

Oregon Scientific WMR100/200/WMRS200/I300/I600/RMS600 protocol.
Latest download URL: http://www.nkl.ru/support/wmr/
Global download URL: http://code.google.com/p/wmr/

Copyright (C) 2012 @Den68 <idg68@yandex.ru>

=cut

wmr_wind=${0##*/}
sensor=${wmr_wind##*_}
wmrconf=${wmrconf:-/etc/wmr/wmr.conf}
autoconfst=0

if [ "$1" = "autoconf" ]; then
        if [ ! -x "`which sqlite3`" ]; then
                echo "no '(sqlite3 not found)'"
                autoconfst=1
	fi

	if [ ! -f $wmrconf ]; then
                echo "no '(" $wmrconf " not found)'"
                autoconfst=1
	fi

	if [ $autoconfst == 0 ]; then
                echo yes
        fi

exit 0
fi

if [ "$1" = "config" ]; then
  echo "graph_category WeatherStation"
  echo "graph_title Wind (WGR800)"
  echo "graph_args --base 1000"
  echo "graph_vlabel m/s / deg"
  echo "wind_speed.label wind speed"
  echo "wind_speed.draw LINE2"
  echo "wind_gust.label wind average"
  echo "wind_gust.draw LINE2"
  echo "wind_dir.label wind direct"
  echo "wind_dir.draw LINE2" 
exit 0
fi

SQLBASEPATH=`cat $wmrconf | grep SQLBASEPATH | awk '{ print $2 }'`
echo "wind_speed.value" `sqlite3 -column ${SQLBASEPATH} "select speed from WIND ORDER BY tdate DESC LIMIT 1"`
echo "wind_gust.value" `sqlite3 -column ${SQLBASEPATH} "select avgspeed from WIND ORDER BY tdate DESC LIMIT 1"`
echo "wind_dir.value" `sqlite3 -column ${SQLBASEPATH} "select dir from WIND ORDER BY tdate DESC LIMIT 1"`

exit 0
