#!/bin/sh
#

: << =cut

=head1 NAME

wmr_temp - Plugin to monitor WMR weather temperature / humidity 
	   sensors THGN801, THGR810 or other...
wmr_temp

=head1 CONFIGURATION

The following enviroment variables are used by this plugin:

 wmrconf - full path to config file to use. (Default /etc/wmr/wmr.conf)

=head1 USAGE

Place the plugin in the /etc/munin/plugins/ directory, and make it
executable.

=head1 AUTHOR

Oregon Scientific WMR100/200/WMRS200/I300/I600/RMS600 protocol.
Latest download URL: http://www.nkl.ru/support/wmr/
Global download URL: http://code.google.com/p/wmr/

Copyright (C) 2012 @Den68 <idg68@yandex.ru>

=cut

wmr_temp=${0##*/}
sensor=${wmr_temp##*_}
wmrconf=${wmrconf:-/etc/wmr/wmr.conf}
autoconfst=0

        if [ ! -x "`which sqlite3`" ]; then
                echo "no '(sqlite3 not found)'"
                exit 0
	fi

	if [ ! -f $wmrconf ]; then
                echo "no '(" $wmrconf " not found)'"
                exit 0
	fi

SQLBASEPATH=`cat $wmrconf | grep SQLBASEPATH | awk '{ print $2 }'`
echo -n "temp_in:"`sqlite3 -column ${SQLBASEPATH} "select temp from TEMP where sensor = 0 ORDER BY tdate DESC LIMIT 1"`
echo -n " temp_out:"`sqlite3 -column ${SQLBASEPATH} "select temp from TEMP where sensor = 1 ORDER BY tdate DESC LIMIT 1"`
echo -n " temp_dew_in:"`sqlite3 -column ${SQLBASEPATH} "select dewpoint from TEMP where sensor = 0 ORDER BY tdate DESC LIMIT 1"`
echo -n " temp_dew_out:"`sqlite3 -column ${SQLBASEPATH} "select dewpoint from TEMP where sensor = 1 ORDER BY tdate DESC LIMIT 1"`
